travis:
  secure:
    BINSTAR_TOKEN: bJo1g7thbJbLU6VUQQ6QDb027G6A4DFRSMzdSUE8DD9DFt3uCNihfrzfbQQSUJi4LxY28qry1cIkWg+mWM/uArl1w77/MJnuw7MyDE46LqcrXLIE1d+hnGWQZvxBD1yiMyhh1U8mcyeAK55cjLXOimh+h1Rh+Hp3H/oLh/M76ScJhZyK+vl5a4o5fnCYFKlXYqXiZnJnH19U5WiCjfYld391LmusLL4plei6UN4EwELG6kISMaH9TaCUV6r9swRcrV0BPK0IO4nSKCMDVZBPSsnfUGfBvYODW2l0noxKrcKSNVpiWv6NYvT4em8oIrSmtRn19Mc9WLweY3gbPrChp82fL/eZw9dHfAIcXA2QXUlfXslbQakWzaleNpBn/VEUaCWbHhIhpQCmhSGP2oBLLPe4Fg2iGUxvxATYv7x5CMc5FQGPBXr8mSpbrFNTV3BWmeetWY9XiRsLYWXFRavZyKxU4c5v0dwvgStECQ7egYEPZFkNywqx5OcgMV031x6jPT1vjmiXFLr6iaryutH2EzJjK1/RzB71GjwmVufuiAWXEi6nLKF/Mau9Q0hpDB3tAd6WiKxMxT2jE2EXtZ9S459Ou9E0rNIYuJcgiwyV6ec69vnkvwqC7yYRdQYLa38DKJRwkrCUxyV10LIwecyD59QVB+lKht44+NQsnXNtmBk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
